package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Position implements Serializable
{
	private static final long serialVersionUID = 8953628789922737905L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_ID
	 * 
	 * @mbggenerated
	 */
	private String positionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String zzjgId;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.ZZJG_ID
	 * 是否优才职位的标志位
	 * 
	 */
	private String isuniposition;

	/**
	 * 
	 * 
	 */
	private String positionZsdw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_NAME
	 * 
	 * @mbggenerated
	 */
	private String positionName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_TYPE
	 * 
	 * @mbggenerated
	 */
	private String positionType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_WORKADDRESS
	 * 
	 * @mbggenerated
	 */
	private String positionWorkaddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_STATUS
	 * 
	 * @mbggenerated
	 */
	private String positionStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date positionAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Integer positionDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_XLYQ
	 * 
	 * @mbggenerated
	 */
	private String positionXlyq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_ZPZY
	 * 
	 * @mbggenerated
	 */
	private String positionZpzy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_XQRS
	 * 
	 * @mbggenerated
	 */
	private String positionXqrs;
	private String positionZylb;
	private String positionZpfl;
	private String positionCanEdit;
	
	/** 
	* @Fields: positionSpepol :特殊支持政策 
	*/ 
	private String positionSpepol;
	
	/** 
	* @Fields: payLow : 薪酬范围 ，最低，最高 
	*/ 
	private String payLow;
	private String payHigh;

	public String getPositionCanEdit()
	{
		return positionCanEdit;
	}

	public void setPositionCanEdit(String positionCanEdit)
	{
		this.positionCanEdit = positionCanEdit;
	}

	public String getPositionZylb()
	{
		return positionZylb;
	}

	public void setPositionZylb(String positionZylb)
	{
		this.positionZylb = positionZylb;
	}

	public String getPositionId()
	{
		return positionId;
	}

	public void setPositionId(String positionId)
	{
		this.positionId = positionId;
	}

	public String getZzjgId()
	{
		return zzjgId;
	}

	public void setZzjgId(String zzjgId)
	{
		this.zzjgId = zzjgId;
	}

	/**
	 * @return the isuniposition
	 */
	public String getIsuniposition() {
	    return isuniposition;
	}

	/**
	 * @param isuniposition the isuniposition to set
	 */
	public void setIsuniposition(String isuniposition) {
	    this.isuniposition = isuniposition;
	}

	public String getPositionZsdw()
	{
		return positionZsdw;
	}

	public void setPositionZsdw(String positionZsdw)
	{
		this.positionZsdw = positionZsdw;
	}

	public String getPositionName()
	{
		return positionName;
	}

	public void setPositionName(String positionName)
	{
		this.positionName = positionName;
	}

	public String getPositionType()
	{
		return positionType;
	}

	public void setPositionType(String positionType)
	{
		this.positionType = positionType;
	}

	public String getPositionWorkaddress()
	{
		return positionWorkaddress;
	}

	public void setPositionWorkaddress(String positionWorkaddress)
	{
		this.positionWorkaddress = positionWorkaddress;
	}

	public String getPositionStatus()
	{
		return positionStatus;
	}

	public void setPositionStatus(String positionStatus)
	{
		this.positionStatus = positionStatus;
	}

	public Date getPositionAddtime()
	{
		return positionAddtime;
	}

	public void setPositionAddtime(Date positionAddtime)
	{
		this.positionAddtime = positionAddtime;
	}

	public Integer getPositionDelflag()
	{
		return positionDelflag;
	}

	public void setPositionDelflag(Integer positionDelflag)
	{
		this.positionDelflag = positionDelflag;
	}

	public String getPositionXlyq()
	{
		return positionXlyq;
	}

	public void setPositionXlyq(String positionXlyq)
	{
		this.positionXlyq = positionXlyq;
	}

	public String getPositionZpzy()
	{
		return positionZpzy;
	}

	public void setPositionZpzy(String positionZpzy)
	{
		this.positionZpzy = positionZpzy;
	}

	public String getPositionZpfl()
	{
		return positionZpfl;
	}

	public void setPositionZpfl(String positionZpfl)
	{
		this.positionZpfl = positionZpfl;
	}

	public String getPositionXqrs()
	{
		return positionXqrs;
	}

	public void setPositionXqrs(String positionXqrs)
	{
		this.positionXqrs = positionXqrs;
	}

	/**
	 * @return the positionSpepol
	 */
	public String getPositionSpepol() {
	    return positionSpepol;
	}

	/**
	 * @param positionSpepol the positionSpepol to set
	 */
	public void setPositionSpepol(String positionSpepol) {
	    this.positionSpepol = positionSpepol;
	}

	/**
	 * @return the payLow
	 */
	public String getPayLow() {
	    return payLow;
	}

	/**
	 * @param payLow the payLow to set
	 */
	public void setPayLow(String payLow) {
	    this.payLow = payLow;
	}

	/**
	 * @return the payHigh
	 */
	public String getPayHigh() {
	    return payHigh;
	}

	/**
	 * @param payHigh the payHigh to set
	 */
	public void setPayHigh(String payHigh) {
	    this.payHigh = payHigh;
	}

}